pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

dependencyResolutionManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		maven {
			name = 'TerraformersMC'
			url = 'https://maven.terraformersmc.com/releases/'
		}
		mavenCentral()
	}
}

rootProject.name = 'player-ping-display'
